### ISSUE TITLE
Run full REST test suite in CI

### ISSUE THREAD

**Issue by smithfarm** [smithfarm/dochazka#10]
According to https://docs.travis-ci.com/user/database-setup/ it is possible to run a PostgreSQL server inside Travis CI. Let's investigate that.

If that turns out to be impossible, fall back to Jenkins in ci.opensuse.org or ci.suse.de.

**Comment by tampakrap** [comment]
done with postgresql in travis

**Comment by smithfarm** [comment]
@tampakrap Congratulations! This is really useful.
