### ISSUE TITLE
Systemd unit file for App::Dochazka::WWW

### ISSUE THREAD

**Issue by smithfarm** [smithfarm/dochazka#12]
Please add a systemd unit file to App::Dochazka::WWW like you just did for REST, including packaging and run it on the server.

**Comment by tampakrap** [comment]
in theory, -www and -rest could run in different machines right? If yes, then we will need different shell users for each one of those services to run them

**Comment by smithfarm** [comment]
good point, maybe `dochazka-rest` and `dochazka-www` would be good for the users as well as for the config directories in `/etc`

**Comment by tampakrap** [comment]
okay on it

**Comment by tampakrap** [comment]
what's the command plus args to start the dochazka-www service?

**Comment by smithfarm** [comment]
`/usr/bin/dochazka-www` with no arguments

**Comment by smithfarm** [comment]
(unless we decide we need Starman, but that would require additional work)

**Comment by tampakrap** [comment]
done
