### ISSUE TITLE
Dochazka trello board

### ISSUE THREAD

**Issue by smithfarm** [smithfarm/dochazka#3]
$SUBJ says it all. Enable github power-up.

**Comment by tampakrap** [comment]
do you want it under the SUSE org?

**Comment by smithfarm** [comment]
Yeah. Until we have a Dochazka contributor from outside the company.

**Comment by tampakrap** [comment]
done and added you. The github power-up you mentioned is on the trello board settings or on each github repo side?

**Comment by smithfarm** [comment]
Excellent! I enabled the power-up, I think. It's in the menu under "Power-ups".

**Comment by smithfarm** [comment]
I also set up some lists/piles along the lines of the "Kanban" system we use in the Ceph team.
