### ISSUE TITLE
enable CI

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka#4]
we need to enable travis-ci since pretty much all of the dochazka apps (and maybe their deps as well) provide tests

**Comment by smithfarm** [comment]
Can you provide a VM for the travis-ci? That would be cool. Running the dochazka-rest test suite requires:
- postgresql installed and postgresql.service running
- a bunch of additional Perl modules - Test::More, etc.
- ability to run the `dochazka-resetdb` script without user input (currently it requires that the user type in the password of the `postgres` user)

The `dochazka-cli` test suite needs:
- a reachable dochazka-rest server

Not completely trivial, but doable I guess!

**Comment by tampakrap** [comment]
I don't know if we can run our own VM, but I'm pretty sure that we can install postgres on travis. If we hit any limitations, we have the ability to mirror the repos in gitlab (gitlab.o.o or gitlab.suse.de) and run the tests on gitlab-ci or jenkins where we will be more flexible. I'll check and report back.

Meanwhile, please enable travis-ci on the settings of all of the repos (inluding the mfile/mrest/cell libs)

**Comment by tampakrap** [comment]
done
