### ISSUE TITLE
factory and leap 42.2 SRs progress

### ISSUE THREAD

**Issue by tampakrap** [smithfarm/dochazka#5]
This is a meta ticket, to track the progress of the factory and 42.2 submissions.

Current status in Application:Dochazka: Done tumbleweed, WIP Leap 42.2, SLES12SP1, 13.2

@smithfarm since I noticed you are one of the owners of devel:languages:perl, please accept all of the SRs I submitted there (OBS is currently down and I can't provide URL :( )

**Comment by tampakrap** [comment]
all the packages are now in their way to factory and 42.2, crossing fingers!

**Comment by smithfarm** [comment]
Good, you noticed that I accepted the d:l:p SRs

**Comment by tampakrap** [comment]
Application:Dochazka is not a valid devel repo, need to push/convince people to do it

**Comment by smithfarm** [comment]
You need to open a PR like this one: https://github.com/openSUSE/osc-plugin-factory/pull/455

**Comment by smithfarm** [comment]
For more info, read https://en.opensuse.org/openSUSE:How_to_contribute_to_Factory#How_to_request_a_new_devel_project

**Comment by smithfarm** [comment]
Once the osc-plugin-factory PR has been merged, you will be able to submit to Factory from Applications:Dochazka

And openSUSE:Factory can be the devel project for Leap.

**Comment by tampakrap** [comment]
https://github.com/openSUSE/osc-plugin-factory/pull/566

**Comment by tampakrap** [comment]
I removed the NOTES file from perl-App-Dochazka-REST:

```
If you re-generate the spec file using, e.g., 'cpanspec -f *gz'
the Source line will need to be changed to:

    Source:         App-Dochazka-REST-%{version}.tar.gz

Also, regenerating the spec file will cause the following lines to disappear:

    Requires:   postgresql-server
```

**Comment by smithfarm** [comment]
> I removed the NOTES file from perl-App-Dochazka-REST

+1

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3L8V5THK&#x2F;3-submit-packages-to-factory-and-leap"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> submit packages to Factory and Leap</a>

**Comment by tampakrap** [comment]
Till the packages get approved in Factory and Leap, let's not touch them in the devel repos please. The leap checks are very sensitive (eg the SR has to have the same sources as the factory SR etc). Thus, SRs against the devel packages are welcome, but they will be on freeze till we get our packages approved. This freeze includes also our devel:language:perl dependencies

**Comment by tampakrap** [comment]
https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:424 https://build.opensuse.org/project/monitor/openSUSE:Leap:42.2:Staging:adi:27 factory is fine, leap needs more work

**Comment by tampakrap** [comment]
due to the complexity on combiningthe leap/sle old perl and the factory perl modules, I decided to submit only dochazka-cli to leap

**Comment by tampakrap** [comment]
I created https://build.opensuse.org/project/show/Application:Dochazka:staging it will be the repo that I will use to linkpac to NPI till we get the packages submitted to factory and leap, and unfreeze Application:Dochazka. Then I will remove :staging and change the links in NPI back to Application:Dochazka. @smithfarm please re-submit your SRs there

**Comment by smithfarm** [comment]
> please re-submit your SRs there

@tampakrap Done https://build.opensuse.org/project/requests/Application:Dochazka:staging

**Comment by tampakrap** [comment]
```
found conflict of clusterssh-4.02.01-6.3.noarch with perl-App-Dochazka-REST-0.531-3.1.noarch: - /usr/lib/perl5/vendor_perl/5.24.0/App [mode mismatch: d755 root:root, d755 dochazka:dochazka]
found conflict of perl-App-Ack-2.15_02-1.3.noarch with perl-App-Dochazka-REST-0.531-3.1.noarch: - /usr/lib/perl5/vendor_perl/5.24.0/App [mode mismatch: d755 root:root, d755 dochazka:dochazka]
```

**Comment by tampakrap** [comment]
perl-App-Dochazka-CLI and dependencies are released in Tumbleweed

**Comment by tampakrap** [comment]
also in Leap. The server components (-REST and -WWW) that are submitted only to factory will take some time though till they pass the legal review

**Comment by smithfarm** [comment]
This is now done, right?

**Comment by tampakrap** [comment]
yes
